# This file contains values from Cookiecutter

default_context:
  project_name: "bento2seldon"
  project_description: "This project aims to combine the awesome capabilities of BentoML in packaging models with the powerful Seldon Core engine to deploy such models. It also features an optional cache using Redis that can also be used to make the feedback loop easier by using the request ID to get back the original request and response. For now, it was created for internal use and is in alpha state. But it will soon be prepared to be used by everyone."
  organization: "fernandocamargoai"
  license: "Apache Software License 2.0"
  version: "0.1.0"
  github_name: "fernandocamargoai"
  email: "fernando.camargo.ai@gmail.com"
